module SSHData
  module PrivateKey
    PEM_TYPE = "OPENSSH PRIVATE KEY"

    # Calculate the fingerprint of a private key, as generated by ssh-keygen.
    #
    # key  - An OpenSSH private key.
    # md5: - Bool of whether to generate an MD5 fingerprint instead of the
    #        default SHA256.
    #
    # Returns a String fingerprint.
    def self.fingerprint(key, md5: false)
      raw = Encoding.decode_pem(key, PEM_TYPE)

      data, read = Encoding.decode_openssh_private_key(raw)
      unless read == raw.bytesize
        raise DecodeError, "unexpected trailing data"
      end

      # make sure public keys match private keys
      pubs = data[:public_keys].map { |raw| PublicKey.parse_raw(raw) }
      privs = from_data(data)
      pubs_from_privs = privs.map { |priv| priv.public_key }
      if pubs != pubs_from_privs
        raise DecodeError, "bad public keys in private key"
      end

      data[:public_keys].map { |raw| PublicKey.raw_fingerprint(raw, md5: md5) }
    end

    # Parse an SSH private key.
    #
    # key - An PEM encoded OpenSSH private key.
    #
    # Returns an Array of PrivateKey::Base subclass instances.
    def self.parse(key)
      raw = Encoding.decode_pem(key, PEM_TYPE)

      data, read = Encoding.decode_openssh_private_key(raw)
      unless read == raw.bytesize
        raise DecodeError, "unexpected trailing data"
      end

      from_data(data)
    end

    def self.from_data(data)
      data[:private_keys].map do |priv|
        case priv[:algo]
        when PublicKey::ALGO_RSA
          RSA.new(**priv)
        when PublicKey::ALGO_DSA
          DSA.new(**priv)
        when PublicKey::ALGO_ECDSA256, PublicKey::ALGO_ECDSA384, PublicKey::ALGO_ECDSA521
          ECDSA.new(**priv)
        when PublicKey::ALGO_ED25519
          ED25519.new(**priv)
        else
          raise DecodeError, "unkown algo: #{priv[:algo].inspect}"
        end
      end
    end
  end
end

require "ssh_data/private_key/base"
require "ssh_data/private_key/rsa"
require "ssh_data/private_key/dsa"
require "ssh_data/private_key/ecdsa"
require "ssh_data/private_key/ed25519"
