module SSHData
  module PublicKey
    # Public key algorithm identifiers
    ALGO_RSA      = "ssh-rsa"
    ALGO_DSA      = "ssh-dss"
    ALGO_ECDSA256 = "ecdsa-sha2-nistp256"
    ALGO_ECDSA384 = "ecdsa-sha2-nistp384"
    ALGO_ECDSA521 = "ecdsa-sha2-nistp521"
    ALGO_ED25519  = "ssh-ed25519"

    # Calculate the fingerprint of a public key, as generated by ssh-keygen.
    #
    # key  - An SSH formatted public key, including algo, encoded key and optional
    #        user/host names.
    # md5: - Bool of whether to generate an MD5 fingerprint instead of the
    #        default SHA256.
    #
    # Returns a String fingerprint.
    def self.fingerprint(key, md5: false)
      _, raw, _ = SSHData.key_parts(key)

      if md5
        # colon separated, hex encoded md5 digest
        OpenSSL::Digest::MD5.digest(raw).unpack("H2" * 16).join(":")
      else
        # base64 encoded sha256 digest with b64 padding stripped
        Base64.strict_encode64(OpenSSL::Digest::SHA256.digest(raw))[0...-1]
      end
    end

    # Parse an SSH public key.
    #
    # key - An SSH formatted public key, including algo, encoded key and optional
    #       user/host names.
    #
    # Returns a PublicKey::Base subclass instance.
    def self.parse(key)
      algo, raw, _ = SSHData.key_parts(key)
      parsed = parse_raw(raw)

      if parsed.algo != algo
        raise DecodeError, "algo mismatch: #{parsed.algo.inspect}!=#{algo.inspect}"
      end

      parsed
    end

    # Parse an SSH public key.
    #
    # key - A raw binary public key String.
    #
    # Returns a PublicKey::Base subclass instance.
    def self.parse_raw(raw)
      data, read = Encoding.decode_public_key(raw)

      if read != raw.bytesize
        raise DecodeError, "unexpected trailing data"
      end

      from_data(data)
    end

    def self.from_data(data)
      case data[:algo]
      when ALGO_RSA
        RSA.new(**data)
      when ALGO_DSA
        DSA.new(**data)
      when ALGO_ECDSA256, ALGO_ECDSA384, ALGO_ECDSA521
        ECDSA.new(**data)
      when ALGO_ED25519
        ED25519.new(**data)
      else
        raise DecodeError, "unkown algo: #{data[:algo].inspect}"
      end
    end
  end
end

require "ssh_data/public_key/base"
require "ssh_data/public_key/rsa"
require "ssh_data/public_key/dsa"
require "ssh_data/public_key/ecdsa"
require "ssh_data/public_key/ed25519"
